trigger: none

parameters:
- name: tfPlanOnly
  displayName: Terraform plan only (no apply)
  type: boolean
  default: true

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: |
    set -e
    curl -sLo tf.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
    unzip -o tf.zip
    sudo mv terraform /usr/local/bin/terraform
    terraform -version
  displayName: Install Terraform 1.6.6

# Plan
- task: AWSShellScript@1
  displayName: Terraform init + plan
  inputs:
    awsCredentials: 'SAMCObservability-492046385895-DEVOPSIACSCVPC-us-east-1-Infrastructure Operations'  # EDIT if your name differs
    regionName: 'us-east-1'
    scriptType: 'bash'
    inlineScript: |
      set -e
      terraform init -input=false
      terraform validate
      terraform plan -input=false -var-file vars/sandbox.tfvars -out tf.plan

- publish: tf.plan
  artifact: tfplan

# Apply (only when tfPlanOnly = false)
- ${{ if not(parameters.tfPlanOnly) }}:
  - task: AWSShellScript@1
    displayName: Terraform apply
    inputs:
      awsCredentials: 'SAMCObservability-492046385895-DEVOPSIACSCVPC-us-east-1-Infrastructure Operations'  # same as above
      regionName: 'us-east-1'
      scriptType: 'bash'
      inlineScript: |
        set -e
        terraform apply -input=false -auto-approve tf.plan
