variable "ecr_tags" {
  description = "A mapping of tags to assign to all resources"
  type        = map(string)
  default     = {}
}

variable "ecr_name" {
  description = "Defines the name of the ECR repository."
  type        = string
  validation {
    condition     = can(regex("^[a-z0-9_-]+$", var.ecr_name))
    error_message = "The  variable must contain only lower cases, numbers, underscore, hyphens"
  }
}

variable "lifecycle_policy" {
  description = "Lifecycle policy to be applied on private ecr repository"
  type        = map(any)
  default     = null

}

variable "image_tag_mutability" {
  type        = string
  description = "Defines whether image tags must be mutable or immutable"
  default     = "MUTABLE"
  validation {
    condition     = contains(["MUTABLE", "IMMUTABLE"], var.image_tag_mutability)
    error_message = "Value should be either MUTABLE or IMMUTABLE."
  }

}
