ecr_tags             = {}
image_tag_mutability = "MUTABLE"
ecr_name             = "test-container"
lifecycle_policy     = null
env                  = "sandbox"
region               = "us-east-1"
appname = "ClientUptime"
