│   with module.canary.module.canary-promerit-demo-sit.module.alarm_aggregator.module.iam-controls.aws_iam_policy.manage_lambda_actions[0],
│   on iam-controls/modules/alarm_aggregator_iam_policy.tf line 1, in resource "aws_iam_policy" "manage_lambda_actions":
│    1: resource "aws_iam_policy" "manage_lambda_actions" {
│ 
╵
╷
│ Error: creating IAM Role (clientuptime-sandbox-demo-promerit-sit-sc-lambda-access-agg-43gK): operation error IAM: CreateRole, https response error StatusCode: 409, RequestID: dfc2c4ed-3b6b-4773-b8fc-590300cc136d, EntityAlreadyExists: Role with name clientuptime-sandbox-demo-promerit-sit-sc-lambda-access-agg-43gK already exists.
│ 
│   with module.canary.module.canary-promerit-demo-sit.module.alarm_aggregator.module.iam-controls.aws_iam_role.aggregator_lambda[0],
│   on iam-controls/modules/alarm_aggregator_iam_role_for_lambda.tf line 1, in resource "aws_iam_role" "aggregator_lambda":
│    1: resource "aws_iam_role" "aggregator_lambda" {
│ 
╵
╷
│ Error: creating IAM Role (demo-promerit-sit-execution-role): operation error IAM: CreateRole, https response error StatusCode: 409, RequestID: d2af54b4-35f7-4555-9b3c-774aa70adc1d, EntityAlreadyExists: Role with name demo-promerit-sit-execution-role already exists.
│ 
│   with module.canary.module.canary-promerit-demo-sit.module.iam-controls-for-canary-synthetic.aws_iam_role.Synthetics_Lambda_Execution_Role[0],
│   on iam-controls/modules/canary_syntetics_iam_policy_document.tf line 1, in resource "aws_iam_role" "Synthetics_Lambda_Execution_Role":
│    1: resource "aws_iam_role" "Synthetics_Lambda_Execution_Role" {
│ 
╵
╷
│ Error: creating S3 Bucket (samc-***-clientuptime-sandbox-demo-promerit-sit-artifact): BucketAlreadyExists
│ 
│   with module.canary.module.canary-promerit-demo-sit.module.s3_artifact_location_bucket.module.s3.aws_s3_bucket.this[0],
│   on s3/terraform-3.1.0-s3-bucket/main.tf line 14, in resource "aws_s3_bucket" "this":
│   14: resource "aws_s3_bucket" "this" {
│ 
╵
##[error]Error: The process '/ADOagent/_work/_tool/terraform/1.9.8/x64/terraform' failed with exit code 1
Finishing: Terraform Apply - TACSyV
