samc-dev-synthetics-role – trusted: synthetics.amazonaws.com, lambda.amazonaws.com; perms: s3:*, logs:*, cloudwatch:*, xray:*.

samc-dev-uptime-lambda-role – trusted: lambda.amazonaws.com; perms: s3:*, logs:*, cloudwatch:*, quicksight:*, xray:*.

samc-dev-scheduler-role – trusted: scheduler.amazonaws.com; perms: lambda:InvokeFunction.
