Skip to main content
Azure DevOps
samcado
/
Infrastructure Operations
/
Pipelines
/
Client-Uptime-Report-obs (2796)
/
20251012.12
Search





Account manager for Brenda Kenne
Infrastructure Operations

Overview

Repos

Pipelines
Pipelines
Environments
Releases
Library
Task groups
Deployment groups
Build Tags

Artifacts

Portfolio++

7pace Timetracker
Project settings

Jobs in run #20251012.12
Terraform Pipeline (SitusAMC DevOps) - SiADoT

  artifactory_user: $[ variablegroups.ArtifactoryReadOnlyAcct.artifactory_user ]
  AZ_GIT_USERNAME: $[ variablegroups.AzureGitCreds.AZ_GIT_USERNAME ]
  AZ_GIT_PAT: $[ variablegroups.AzureGitCreds.AZ_GIT_PAT ]
ContinueOnError: False
TimeoutInMinutes: 0
CancelTimeoutInMinutes: 5
Expand:
  MaxConcurrency: 0
  ########## System Pipeline Decorator(s) ##########

  Begin evaluating template 'system-pre-steps.yml'
Evaluating: eq('true', variables['system.debugContext'])
Expanded: eq('true', Null)
Result: False
Evaluating: resources['repositories']['self']
Expanded: Object
Result: True
Evaluating: not(containsValue(job['steps']['*']['task']['id'], '6d15af64-176c-496d-b583-fd2ae21d4df4'))
Expanded: not(containsValue(Object, '6d15af64-176c-496d-b583-fd2ae21d4df4'))
Result: False
Finished evaluating template 'system-pre-steps.yml'
********************************************************************************
Template and static variable resolution complete. Final runtime YAML document:
steps: []


  MaxConcurrency: 0
Parent pipeline used these runtime parameters
Sandbox : "true"
terraformPlanOnly : "True"

Row 3

Showing 25 filtered items.

Get started and run this pipeline for the first time!

Showing 33 filtered items.

Showing 25 filtered items.

Row 2

Row 2

Row 2

Showing 10 filtered items.

Get started and run this pipeline for the first time!

Row 2

Row 3
