variable "email_list" {
  type = list(string)
}

variable "pagerduty_ep" {
  type = string
}





# existing entries you already have …
env          = "sandbox"
appname      = "ClientUptime"
region       = "us-east-1"       # only once
network_type = "production"      # or whatever you use

# NEW — satisfy required inputs
email_list   = ["alerts@example.com", "oncall@example.com"]  # list of emails
pagerduty_ep = "pd-oncall@example.com"                       # or your PD integration email/URL
