module.canary.module.canary-promerit-demo-sit.module.iam-controls-for-canary-synthetic.data.aws_iam_policy_document.db_refresh_cross_account_backup_bucket_policy: Reading...
module.canary.module.canary-promerit-demo-sit.module.alarm_aggregator.data.template_file.lambda_handler: Reading...
module.canary.module.canary-promerit-demo-sit.module.iam-controls-for-canary-synthetic.data.template_file.api_gateway_resource_policy_json: Reading...
module.canary.module.canary-promerit-demo-sit.module.iam-controls-for-canary-synthetic.data.aws_iam_policy_document.bedrocklogs-eoa1nn: Read complete after 0s [id=4205690576]
module.canary.module.canary-promerit-demo-sit.module.alarm_aggregator.module.iam-controls.data.aws_iam_policy_document.elb_access_logs: Read complete after 0s [id=234552206]
module.canary.module.canary-promerit-demo-sit.module.alarm_aggregator.data.template_file.lambda_handler: Read complete after 0s [id=813db593f12bd0017c2637d891a272c86a6d936b7f99c6d0a2a24711d15e7250]
module.canary.module.canary-promerit-demo-sit.module.iam-controls-for-canary-synthetic.data.template_file.api_gateway_resource_policy_json: Read complete after 0s [id=e7b3f7647baecdc24b2a487185680bf851c58f28967e225d6da79726c471b765]
module.canary.module.canary-promerit-demo-sit.module.iam-controls-for-canary-synthetic.data.aws_iam_policy_document.s3_mssql_backup_bucket_policy: Read complete after 0s [id=2135457337]
module.canary.module.canary-promerit-demo-sit.module.iam-controls-for-canary-synthetic.data.aws_iam_policy_document.db_refresh_cross_account_backup_bucket_policy: Read complete after 0s [id=2063967210]
module.canary.module.canary-promerit-demo-sit.module.alarm_aggregator.module.iam-controls.data.aws_iam_policy_document.bedrocklogs-eoa1nn: Reading...
module.canary.module.canary-promerit-demo-sit.module.s3_artifact_location_bucket.module.s3.data.aws_iam_policy_document.combined[0]: Reading...
module.canary.module.canary-promerit-demo-sit.module.alarm_aggregator.module.iam-controls.data.aws_iam_policy_document.bedrocklogs-eoa1nn: Read complete after 0s [id=4205690576]
module.canary.module.canary-promerit-demo-sit.module.s3_artifact_location_bucket.module.s3.data.aws_iam_policy_document.combined[0]: Read complete after 0s [id=2141534231]
╷
│ Warning: Deprecated attribute
│ 
│   on s3/terraform-3.1.0-s3-bucket/main.tf line 26, in resource "aws_s3_bucket" "this":
│   26:       acceleration_status,
│ 
│ The attribute "acceleration_status" is deprecated. Refer to the provider
│ documentation for details.
│ 
│ (and 2 more similar warnings elsewhere)
╵
╷
│ Error: reading ECR Repository (client-uptime-lambda): operation error ECR: DescribeRepositories, https response error StatusCode: 400, RequestID: b43cc5b8-a1c5-4b29-834f-a05fe3a1db19, api error AccessDeniedException: User: arn:aws:iam::492046385895:user/DEVOPSIACSVCVPC is not authorized to perform: ecr:DescribeRepositories on resource: arn:aws:ecr:***:492046385895:repository/client-uptime-lambda because no identity-based policy allows the ecr:DescribeRepositories action
│ 
│ 
╵
##[error]Error: The process '/ADOagent/_work/_tool/terraform/1.9.8/x64/terraform' failed with exit code 1
Finishing: Terraform destroy
