module "s3_bucket" {
  source = "git::ssh://git@ssh.dev.azure.com:22/v3/samcado/Infrastructure%20Operations/DEVOPS_Platform_as_a_Service/s3//terraform-3.1.0-s3-bucket?ref=refs/tags/4.2.0"

  bucket_name        = "client-uptime-report-obs-artifacts"
  versioning_enabled = true
  # ...other required inputs
}
