-rw-r--r-- 1 vsts vsts 3349 Oct  7 17:47 s3.tf
-rw-r--r-- 1 vsts vsts 2975 Oct  7 17:47 variables.tf
terraform init (moduleRef=refs/tags/4.2.0)
Initializing the backend...
Initializing modules...
Downloading git::https://samcado.visualstudio.com/DEVOPS_Platform_as_a_Service/_git/s3?ref=refs/tags/4.2.0 for s3...
- s3 in .terraform/modules/s3/terraform-3.1.0-s3-bucket
╷
│ Error: Terraform encountered problems during initialisation, including problems
│ with the configuration, described below.
│ 
│ The Terraform configuration must be valid before initialization so that
│ Terraform can determine which modules and providers need to be installed.
│ 
│ 
╵
╷
│ Error: Argument or block definition required
│ 
│   on s3.tf line 55, in resource "aws_s3_bucket_acl" "this":
│   55:     ? 0
│ 
│ An argument or block definition is required here.
╵

##[error]Error: The process '/usr/bin/bash' failed with exit code 1
Finishing: Terraform init/plan/apply (AWS creds)
