variable "artifactory_user" {
  description = "READ ONLY JFrog user account - used to download CarbonBlack and Nessus agents from JFrog"
  type        = string
}

variable "artifactory_pass" {
  description = "READ ONLY JFrog user acount's pwd - used to download CarbonBlack and Nessus agents from JFrog"
  type        = string
}

variable "region" {
  type    = string
  default = "us-east-1"
}

variable "env" {
  type = string
}

variable "appname" {
  type = string
}

variable "network_type" {
  type = string
}

variable "email_list" {
  type = list(string)
}

# PagerDuty only required in production; optional elsewhere
variable "pagerduty_ep" {
  type    = string
  default = ""
}

# ADD: matches your tfvars (removes the undeclared-variable warning)
variable "lifecycle_policy" {
  type    = any
  default = null
}

# ADD: lets you turn off any ECR lookups in this stack (avoids AccessDenied on plan)
variable "enable_ecr" {
  type    = bool
  default = false
}
