-rw-r--r-- 1 vsts vsts 3917 Oct  7 17:52 azure-pipeline.yml
-rw-r--r-- 1 vsts vsts 1371 Oct  7 17:52 dev.tfvars
-rw-r--r-- 1 vsts vsts  205 Oct  7 17:52 providers.tf
-rw-r--r-- 1 vsts vsts 2793 Oct  7 17:52 s3.tf
-rw-r--r-- 1 vsts vsts 2975 Oct  7 17:52 variables.tf
terraform init (moduleRef=refs/tags/4.2.0)
Initializing the backend...
Initializing modules...
╷
│ Error: Unsuitable value type
│ 
│   on s3.tf line 10, in module "s3":
│   10:   source = "git::https://samcado.visualstudio.com/DEVOPS_Platform_as_a_Service/_git/s3//terraform-3.1.0-s3-bucket?ref=${var.module_ref}"
│ 
│ Unsuitable value: value must be known
╵
╷
│ Error: Variables not allowed
│ 
│   on s3.tf line 10, in module "s3":
│   10:   source = "git::https://samcado.visualstudio.com/DEVOPS_Platform_as_a_Service/_git/s3//terraform-3.1.0-s3-bucket?ref=${var.module_ref}"
│ 
│ Variables may not be used here.
╵

##[error]Error: The process '/usr/bin/bash' failed with exit code 1
Finishing: Terraform init/plan/apply (AWS creds)
