# gitCheckout.yml
steps:
- checkout: self
  displayName: "Checkout self"

- checkout: synthetic-canary-alarm
  displayName: "Checkout synthetic-canary-alarm"

- checkout: sns-subtopic
  displayName: "Checkout sns-subtopic"

- checkout: alarm-aggregator
  displayName: "Checkout alarm-aggregator"

- checkout: s3
  displayName: "Checkout s3"

- checkout: iam-controls
  displayName: "Checkout iam-controls"
