variable "region" {
  type    = string
  default = "us-east-1"
}

variable "env" {
  type = string
}

variable "appname" {
  type = string
}

variable "email_list" {
  type = list(string)
}

variable "pagerduty_ep" {
  type = string
}

variable "network_type" {
  type = string
}
