# gitCheckout.yml
steps:
- checkout: self
  path: s/$(Build.Repository.Name)

- checkout: synthetic-canary-alarm
  path: s/$(Build.Repository.Name)/synthetic-canary-alarm

- checkout: sns-subtopic
  path: s/$(Build.Repository.Name)/sns-subtopic

- checkout: alarm-aggregator
  path: s/$(Build.Repository.Name)/alarm-aggregator

- checkout: s3
  path: s/$(Build.Repository.Name)/s3

- checkout: iam-controls
  path: s/$(Build.Repository.Name)/iam-controls
