resources:
  repositories:
    - repository: templates
      type: git
      name: DEVOPS_Platform_as_a_Service/deploy-templates
      ref: refs/tags/6.45.0
    - repository: synthetic-canary-alarm
      type: git
      name: DEVOPS_Platform_as_a_Service/synthetic-canary-alarm
      ref: refs/tags/2.2.0
    - repository: sns-subtopic
      type: git
      name: DEVOPS_Platform_as_a_Service/sns-subtopic
      ref: refs/tags/1.0.0
    - repository: iam-controls
      type: git
      name: DEVOPS_Platform_as_a_Service/iam-controls
      ref: refs/tags/2.27.0
    - repository: alarm-aggregator
      type: git
      name: DEVOPS_Platform_as_a_Service/alarm-aggregator
      ref: refs/tags/2.0.2
    - repository: s3
      type: git
      name: DEVOPS_Platform_as_a_Service/s3
      ref: refs/tags/4.2.0

trigger: none
variables:
- group: ArtifactoryReadOnlyAcct
# optional passthrough (harmless if keys already match)
- name: artifactory_user
  value: $(artifactory_user)
- name: artifactory_pass
  value: $(artifactory_pass)

parameters:
- name: terraformVersion
  displayName: Terraform Version
  type: string
  default: '1.9.8'
- name: terrformPLANonly
  displayName: tfPlanOnly (check == true)
  type: boolean
  default: true
- name: Sandbox
  displayName: Deploy to Sandbox
  type: boolean
  default: false


stages:
- ${{ if eq(parameters.Sandbox, true) }}:
  - template: deploy/tf-create-infra-template.yml@templates
    parameters:
      environment: sandbox
      environmentDisplayName: Sandbox
      tfServiceConnection: SAMCObservability-492046385895-DEVOPSIACSVCVPC-us-east-1-Infrastructure Operations
      awsServiceConnection: SAMCObservability-492046385895-DEVOPSIACSVCVPC-Infrastructure Operations
      tfVersion: ${{ parameters.terraformVersion }}
      application: ClientUptime
      pipelineSrcDir: $(Build.Repository.Name)
      tfPlanOnly: ${{ parameters.terrformPLANonly }}
      regionName: us-east-1
      checkoutTemplate: gitCheckouts.yml
