aws_region  = "us-east-1"
bucket_name = "client-uptime-report-obs-artifacts"

versioning_enabled = true
force_destroy      = false

block_public_acls         = true
block_public_policy       = true
ignore_public_acls        = true
restrict_public_buckets   = true

control_object_ownership  = true
object_ownership          = "BucketOwnerEnforced"

object_lock_enabled       = false
object_lock_configuration = null

lifecycle_rule = [
  {
    id      = "noncurrent-30"
    enabled = true
    noncurrent_version_expiration = {
      days = 30
    }
  }
]

server_side_encryption_configuration = {
  rule = {
    apply_server_side_encryption_by_default = {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = "alias/aws/s3"
    }
  }
}

bucket_policy_json         = null
continuous_backups_enabled = false

tags = {
  env         = "sandbox"
  owner       = "observability"
  application = "client-uptime-report-obs"
}

acl                   = null
grant                 = []
owner                 = {}
expected_bucket_owner = null
