output "critical_notification_sns" {
  value       = aws_sns_topic.appname_env_monitoring_CRITICAL.arn
  description = "SNS topic ARN for CRITICAL (SEVERE) alarms."
}

output "high_notification_sns" {
  value       = aws_sns_topic.appname_env_monitoring_High.arn
  description = "SNS topic ARN for HIGH (ALERT) alarms."
}

output "medium_notification_sns" {
  value       = aws_sns_topic.appname_env_monitoring_medium.arn
  description = "SNS topic ARN for MEDIUM (WARNING) alarms."
}
