variable "network_type" {
  type = string
}

variable "artifactory_user" {
  type = string
}

variable "artifactory_pass" {
  type      = string
  sensitive = true
}



network_type     = var.network_type
artifactory_user = var.artifactory_user
artifactory_pass = var.artifactory_pass
