region       = "us-east-1"
env          = "sandbox"
appname      = "ClientUptime"
network_type = "nonproduction"                # anything not equal to "production"
email_list   = ["brendakenne@situsamc.com"]

# keep only if you want to drive it; otherwise delete this line since default is null
lifecycle_policy = null

# do NOT set pagerduty_ep in nonprod (default "" is fine)

# optional but recommended to avoid ECR permission errors during plan/destroy
enable_ecr = false
