{
  "version": "0",
  "id": "00000000-1111-2222-3333-444444444444",
  "detail-type": "Scheduled Event",
  "source": "aws.events",
  "account": "123456789012",
  "time": "2025-10-08T06:00:00Z",
  "region": "us-east-1",
  "resources": ["arn:aws:events:us-east-1:123456789012:rule/run-uptime-report"],
  "detail": {}
}
