terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {}  # values come from -backend-config=backend.hcl
}

provider "aws" {
  region = var.aws_region
}
