variable "artifactory_user" {
  description = "READ ONLY JFrog user account - used to download CarbonBlack and Nessus agents from JFrog"
  type        = string
}

variable "artifactory_pass" {
  description = "READ ONLY JFrog user acount's pwd - used to download CarbonBlack and Nessus agents from JFrog"
  type        = string
}

variable "region" {
  type    = string
  default = "us-east-1"
}

variable "env" {
  type = string
}

variable "appname" {
  type = string
}

variable "email_list" {
  type = list(string)
}

variable "pagerduty_ep" {
  type    = string
  default = ""    # makes it optional for nonprod
}


variable "network_type" {
  type = string
}
