# using for canary main.tf, commencted root main.tf
region ="us-east-1"

#ecr
// ecr_tags             = {}
// image_tag_mutability = "MUTABLE"
// ecr_name             = "test-container"
lifecycle_policy     = null
env                  = "sandbox"
appname = "ClientUptime"


# canary 
network_type = "nonprod"


email_list   = ["brendakenne@situsamc.com"]   # put real email(s)
