# gitCheckouts.yml
steps:
- checkout: self
  path: .

- checkout: synthetic-canary-alarm
  path: synthetic-canary-alarm

- checkout: sns-subtopic
  path: sns-subtopic

- checkout: alarm-aggregator
  path: alarm-aggregator

- checkout: s3
  path: s3

- checkout: iam-controls
  path: iam-controls
