# # PROMERIT DEMO SIT
module "canary-promerit-demo-sit" {
#   source         = "../synthetic-canary-alarm"
#   appname        = var.appname
#   env            = var.env
#   region         = var.region
#   monitoring_url = "https://demo-promerit-sit.situsamc.com/MBMSWebClient_deploy/mvc/Homepage.aspx"
#   canary_name    = "demo-promerit-sit"

#   critical_notification_sns = module.sns-subtopic.critical_notification_sns
#   high_notification_sns     = module.sns-subtopic.high_notification_sns
#   medium_notification_sns   = module.sns-subtopic.medium_notification_sns
# }
