
Variables:
  artifactory_auth: $[ variablegroups.ArtifactoryReadOnlyAcct.artifactory_auth ]
  artifactory_pass: $[ variablegroups.ArtifactoryReadOnlyAcct.artifactory_pass ]
  artifactory_user: $[ variablegroups.ArtifactoryReadOnlyAcct.artifactory_user ]
  AZ_GIT_USERNAME: $[ variablegroups.AzureGitCreds.AZ_GIT_USERNAME ]
  AZ_GIT_PAT: $[ variablegroups.AzureGitCreds.AZ_GIT_PAT ]
ContinueOnError: False
TimeoutInMinutes: 0
CancelTimeoutInMinutes: 5
Expand:
  MaxConcurrency: 0
  ########## System Pipeline Decorator(s) ##########

  Begin evaluating template 'system-pre-steps.yml'
Evaluating: eq('true', variables['system.debugContext'])
Expanded: eq('true', Null)
Result: False
Evaluating: resources['repositories']['self']
Expanded: Object
Result: True
Evaluating: not(containsValue(job['steps']['*']['task']['id'], '6d15af64-176c-496d-b583-fd2ae21d4df4'))
Expanded: not(containsValue(Object, '6d15af64-176c-496d-b583-fd2ae21d4df4'))
Result: False
Finished evaluating template 'system-pre-steps.yml'
********************************************************************************
Template and static variable resolution complete. Final runtime YAML document:
steps: []


  MaxConcurrency: 0
