resources:
  repositories:
    - repository: templates
      type: git
      name: DEVOPS_Platform_as_a_Service/deploy-templates
      ref: refs/tags/7.7.0

trigger: none

parameters:
- name: tfPlanOnly
  displayName: Terraform plan only (no apply)
  type: boolean
  default: true

stages:
- template: deploy/tf-create-infra-template.yml@templates
  parameters:
    environment: sandbox                      # must equal var.env
    environmentDisplayName: sandbox
    tfServiceConnection: SAMCObservability-492046385895-DEVOPSIACSCVPC-us-east-1-Infrastructure Operations
    awsServiceConnection: SAMCObservability-492046385895-DEVOPSIACSCVPC-Infrastructure Operations
    tfVersion: "1.13.3"
    application: QuickSetup                   # must equal var.appname
    pipelineSrcDir: $(Build.Repository.Name)
    tfPlanOnly: ${{ parameters.tfPlanOnly }}
    regionName: us-east-1                     # must equal var.region
    checkoutTemplate: gitCheckouts.yml
