Help         : Runs a shell script in Bash, setting AWS credentials and region information into the shell environment using the standard environment keys _AWS_ACCESS_KEY_ID_, _AWS_SECRET_ACCESS_KEY_, _AWS_SESSION_TOKEN_ and _AWS_REGION_.

More information on this task can be found in the [task reference](https://docs.aws.amazon.com/vsts/latest/userguide/awsshell.html).

####Task Permissions
Permissions for this task to call AWS service APIs depend on the activities in the supplied script.
==============================================================================
Configuring credentials for task
...configuring AWS credentials from service endpoint '11cf86a4-f69a-4e2d-be1d-f04c57ad0062'
...configuring AWS credentials from service endpoint '11cf86a4-f69a-4e2d-be1d-f04c57ad0062'
Skipping OIDC: not enabled in service connections
...configuring AWS credentials from service endpoint '11cf86a4-f69a-4e2d-be1d-f04c57ad0062'
...endpoint defines standard access/secret key credentials
Configuring region for task
...configured to use region us-east-1, defined in task.
/usr/bin/bash /home/vsts/work/_temp/awsshellscript_2376.sh
Sanity: cross-project repo access (visualstudio.com)
cd to Build.SourcesDirectory/Build.Repository.Name, then into TF working dir
Files here:
total 32
drwxr-xr-x 3 vsts vsts 4096 Oct  7 17:58 .
drwxr-xr-x 3 vsts vsts 4096 Oct  7 17:58 ..
drwxr-xr-x 7 vsts vsts 4096 Oct  7 17:58 .git
-rw-r--r-- 1 vsts vsts 3917 Oct  7 17:58 azure-pipeline.yml
-rw-r--r-- 1 vsts vsts 1371 Oct  7 17:58 dev.tfvars
-rw-r--r-- 1 vsts vsts  205 Oct  7 17:58 providers.tf
-rw-r--r-- 1 vsts vsts 2739 Oct  7 17:58 s3.tf
-rw-r--r-- 1 vsts vsts 2975 Oct  7 17:58 variables.tf
terraform init (moduleRef=refs/tags/4.2.0)
Initializing the backend...
