│ with the configuration, described below.
│ 
│ The Terraform configuration must be valid before initialization so that
│ Terraform can determine which modules and providers need to be installed.
│ 
│ 
╵
╷
│ Error: Argument or block definition required
│ 
│   on s3.tf line 46, in resource "aws_s3_bucket_acl" "this":
│   46:     ? 0
│ 
│ An argument or block definition is required here.
╵
╷
│ Error: Invalid single-argument block definition
│ 
│   on variables.tf line 24, in variable "block_public_acls":
│   24: variable "block_public_acls"          { type = bool default = true }
│ 
│ A single-line block definition must end with a closing brace immediately
│ after its single argument definition.
╵

##[error]Error: The process '/usr/bin/bash' failed with exit code 1
Finishing: Terraform init/plan/apply (AWS creds)
