provider "aws" {
  region = var.region
}

module "canary-promerit-demo-sit" {
  source         = "../synthetic-canary-alarm"

  appname        = var.appname
  env            = var.env
  region         = var.region
  monitoring_url = var.monitoring_url
  canary_name    = var.canary_name

  critical_notification_sns = var.critical_notification_sns
  high_notification_sns     = var.high_notification_sns
  medium_notification_sns   = var.medium_notification_sns
}
