variable "monitoring_url" {
  type = string
}

variable "canary_name" {
  type = string
}

variable "critical_notification_sns" {
  type = string
}

variable "high_notification_sns" {
  type = string
}

variable "medium_notification_sns" {
  type = string
}
