# dev.tfvars — opinionated

aws_region        = "us-east-1"
bucket_name       = "myapp-dev-artifacts"
versioning_enabled = true
force_destroy      = true

# Block all public access in dev (recommended)
block_public_acls       = true
block_public_policy     = true
ignore_public_acls      = true
restrict_public_buckets = true

# Ownership & object-lock
control_object_ownership = true
object_ownership         = "BucketOwnerEnforced"
object_lock_enabled      = false
object_lock_configuration = null

# Simple SSE with S3-managed keys (no KMS setup needed)
server_side_encryption_configuration = {
  rule = {
    apply_server_side_encryption_by_default = {
      sse_algorithm = "AES256"
    }
    bucket_key_enabled = false
  }
}

# Keep dev buckets tidy: transition logs/, expire old versions
lifecycle_rule = [
  {
    id                                   = "expire-old-versions"
    enabled                              = true
    noncurrent_version_expiration = { days = 30 }
    abort_incomplete_multipart_upload_days = 7
    tags = { rule = "expire" }
  },
  {
    id      = "logs-transition"
    enabled = true
    filter  = { prefix = "logs/" }
    transition = [{
      days          = 30
      storage_class = "STANDARD_IA"
    }]
    expiration = { days = 365 }
  }
]

# Leave null unless you truly need a custom JSON policy
bucket_policy_json = null

# Tag-only flag for your reporting
continuous_backups_enabled = false

# ACL/grants/owner: keep defaults locked down in dev
acl   = null
grant = []
owner = {}

# Set to your AWS account ID to enforce ownership, or leave null
expected_bucket_owner = null

# Global tags
tags = {
  Environment = "dev"

}
