resources:
  repositories:
    - repository: s3
      type: git
      name: DEVOPS_Platform_as_a_Service/s3
      ref: refs/tags/4.2.0

trigger: none

# Add groups so the template compiles
variables:
- group: CrossProjectGitPAT
- group: ArtifactoryReadOnlyAcct
- group: AzureGitCreds

parameters:
- name: sandbox
  displayName: Deploy S3 to SAMC
  type: boolean
  default: false
- name: terrformPLANonly
  displayName: tfPlanOnly (check == true)
  type: boolean
  default: false

stages:
- template: deploy/tf-create-infra-template.yml@templates
  parameters:
    environment: SAMC
    environmentDisplayName: SAMC
    tfServiceConnection: SAMCObservability-492046385895-DEVOPSIACSVCVPC-us-east-1-Infrastructure Operations
    awsServiceConnection: SAMCObservability-492046385895-DEVOPSIACSVCVPC-Infrastructure Operations
    tfVersion: 1.13.3
    application: QuickSetup
    pipelineSrcDir: $(Build.Repository.Name)
    tfPlanOnly: ${{ parameters.terrformPLANonly }}
    regionName: us-east-1
    checkoutTemplate: gitCheckouts.yml
