# steps:
# - checkout: synthetic-canary-alarm
#   displayName: Checkout Synthetic Canary Alarm Module

# - checkout: sns-subtopic
#   displayName: Get SNS SubTopic module

# - checkout: iam-controls
#   displayName: Checkout IAM Controls module

# - checkout: alarm-aggregator
#   displayName: Checkout Alarm Aggregator module

# - checkout: s3
#   displayName: Checkout S3 module
