# ecr/gitCheckouts.yml
steps:
- checkout: self
  displayName: Get pipeline repo

- checkout: AWS-ECR
  displayName: Get ECR module - SAMC

# Keep this because shared jobs may expect it present
- checkout: iam-controls
  displayName: Get iam-controls module - SAMC
